site_name: Prism-H
site_description: AI-driven mosquito breeding spot detection and analysis
site_author: ArtPark Team
site_url: https://dsih-artpark.github.io/prism-h-image-classifier

theme:
  name: material
  palette:
    - scheme: default
      primary: blue grey
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue grey
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - search.highlight
    - search.share
    - search.suggest
    - content.code.copy
    - content.code.annotate
    - header.autohide
  font:
    text: Inter
    code: JetBrains Mono

plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [src]
          options:
            show_source: true
            show_root_heading: true
            heading_level: 2
            docstring_style: google
            show_signature_annotations: true
            separate_signature: true

nav:
  - Home: index.md
  - Getting Started:
    - Installation: guide/installation.md
    - Quick Start: guide/quickstart.md
    - Configuration: guide/configuration.md
  - Technical Reference:
    - Core Modules:
      - Image Preprocessing: api/core/preprocess.md
      - Feature Extraction: api/core/extract_embeddings.md
    - Models:
      - SimCLR: api/models/simclr.md
  - Examples:
    - Basic Usage: examples/basic_usage.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - md_in_html
  - def_list
  - footnotes
  - tables
  - toc:
      permalink: true
      title: On this page
      toc_depth: 2

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/dsih-artpark/prism-h-image-classifier
      name: GitHub Repository
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  version:
    provider: mike

extra_css:
  - stylesheets/extra.css
